name: 02 - Workflow Events
on: 
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
  pull_request:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps: 
      - name: show the trigger
        run: echo "type the name ${{ github.event_name }}"
