name: 04-Using Actions
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v6
      - name: printing folders
        run: ls
      - name: read the file
        run: cat README.md

