name: 04-Using Actions
on: 
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./04-using-actions/react-app
    steps: 
      - name: checkout code
        uses: actions/checkout@v6
      - name: printing folders
        run: ls
      - name: read the file
        run: cat README.md
      - name: setup node
        uses: actions/setup-node@v6
        with:   
          node-version: '20.x'
      - name: install dep
        run:  npm ci        
        working-directory: ./04-using-actions/react-app
      - name: run unit test
        run: np  run test  

