name: 06-contexts
run-name: 06-contexts | debug info -${{inputs.debug}}
on: 
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
jobs: 
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Display information
        run: |
          echo "Event name: ${{github.event_name}}"
          echo "Reg: ${{github.ref}}"
          echo "sha ${{github.sha}}"
          echo "actor:  ${{github.actor}}"
          echo "workflow: ${{github.workflow}}"
          echo "runid: ${{github.run_id}}"
          echo "run number: ${{github.run_number}}"

      - name: retrieve vairable
        run: |
          echo "vairable value ${{vars.MY_VAR}}"   
