name: 06-contexts
run-name: 06-contexts | debug info -${{inputs.debug}}
on: 
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

env:
  MY_WORKFLOW_VAR: 'workflow'
  MY_OVERWRITTEN_VAR: 'WORKFLOW-ow'


jobs: 
  echo-data:

    runs-on: ubuntu-latest
    env:
      MY_JOB_VAR: 'JOB'
      MY_OVERWRITTEN_VAR: 'job-ow'
    steps:
      - name: Display information
        run: |
          echo "Event name: ${{github.event_name}}"
          echo "Reg: ${{github.ref}}"
          echo "sha ${{github.sha}}"
          echo "actor:  ${{github.actor}}"
          echo "workflow: ${{github.workflow}}"
          echo "runid: ${{github.run_id}}"
          echo "run number: ${{github.run_number}}"

      - name: retrieve vairable
        run: |
          echo "vairable value ${{vars.MY_VAR}}"  


      - name: prit env vairable
        env:
          MY_OVERWRITTEN_VAR: 'step-ow'
        run: | 
          echo "workflow env: ${{env.MY_WORKFLOW_VAR}}"
          echo "Overwritten env: ${{env.MY_OVERWRITTEN_VAR}}"     

      - name: prit env vairable 2222
        run: | 
          echo "workflow env: ${{env.MY_WORKFLOW_VAR}}"
          echo "Overwritten env: ${{env.MY_OVERWRITTEN_VAR}}"  